### PR TITLE
Fix ios crash

### LINKED ISSUE #83: crash on iOS and iOS-Sim
crashes in the simulator right away and on device on second call:

```
#1	0x00000001853f1a4c in -[UIApplication _openURL:options:completionHandler:] ()
#2	0x0000000104bd7754 in _$LT$$LP$A$C$B$C$C$RP$$u20$as$u20$objc..message..MessageArguments$GT$::invoke::h723bf370353936c5 [inlined] at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/mod.rs:128
#3	0x0000000104bd7744 in objc::message::platform::send_unverified::h633786a288498e5d [inlined] at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/apple/mod.rs:27
#4	0x0000000104bd7744 in objc::message::send_message::h51c0bf550976ad86 [inlined] at /Users/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/mod.rs:178
#5	0x0000000104bd7744 in webbrowser::os::open_browser_internal::h265347fd9891411b at /Users/stephan/code/webbrowser-rs/src/ios.rs:34
#6	0x0000000104bd6ee8 in webbrowser::open_browser_with_options::h4f9ae24e53e16fcc [inlined] at /Users/stephan/code/webbrowser-rs/src/lib.rs:331
#7	0x0000000104bd6eb8 in webbrowser::open_browser::h7ea0b174943835c6 [inlined] at /Users/stephan/code/webbrowser-rs/src/lib.rs:298
#8	0x0000000104bd6eb8 in webbrowser::open::h36cf092bc1244f75 at /Users/stephan/code/webbrowser-rs/src/lib.rs:283
```

### PR DESCRIPTION
**Pull request by extrawurst**
fixes #83

### CODE REVIEW

**Comment by amodm** [comment]
Thanks @extrawurst. Can you please also share what kind of URL was breaking this?

**Comment by amodm** [comment]
This is good to go, but I'll wait to hear about the URL that caused this issue, so that I can modify the tests for it accordingly. The patch release will happen after that.

**Comment by extrawurst** [comment]
you can test this with the `bevy_game_template` using `webbrowser` on iOS Simulator, see the offending URL in there: https://github.com/NiklasEi/bevy_game_template/blob/dcbc44bdc97793040cf5af746d0cbf8b2907dd81/src/menu.rs#L117

**Comment by amodm** [comment]
There are tests that run every time on the sim for iOS (you can check yourself by having a sim on, and running `cargo test --test test_ios -- --include-ignored`. I've run a test just now by modifying `tests/test-ios-app/testglue/src/lib.rs` to include the following:
```rust
let _ = webbrowser::open("https://bevyengine.org");
```

and it ran just fine in the sim (opened that url). Initially I'd thought it's some url with weird characters. Have you verified that this change fixes the issue on your machine?

**Comment by extrawurst** [comment]
> Have you verified that this change fixes the issue on your machine?

yes on sim and device

**Comment by amodm** [comment]
Cool. This is now released as [v0.8.15](https://github.com/amodm/webbrowser-rs/releases/tag/v0.8.15). Thanks for your contribution.

**Comment by amodm** [comment]
@extrawurst, seems to be an issue with the provisioning profile. You may need to open `tests/test-ios-app/test-ios-app.xcodeproj` and check on the xcode configuration. Sometimes Xcode behaves erratically until you "touch" the provisioning profile.

Here's a rundown of the test architecture:
* For ios testing, the "app" being built is `tests/test-ios-app/test-ios-app`
* This uses a rust lib called `testglue` which is under `tests/test-ios-app/testglue`
* `tests/test_ios.rs` invokes cargo build for `testglue`, and xcode to build the `test-ios-app`, and then runs it on the sim

If debugging feels too much work, and you suspect `objc2` is the issue, just log another bug with some reproduction hints, and I'll take a look at it.

**Pull request merged**
