### PR TITLE
Upgrade windows-rs to 0.44

### PR DESCRIPTION
**Pull request by MarijnS95**

### CODE REVIEW

**Comment by amodm** [comment]
Thanks for the contribution. This will be included in the next release, but won't trigger a release on its own.

**Comment by amodm** [comment]
FYI, the `windows` crate dependency has been dropped now altogether, and been replaced with pure FFI bindings, given the very small surface area actually used of it, and is now released as [v0.8.5](https://github.com/amodm/webbrowser-rs/releases/tag/v0.8.5)

**Comment by MarijnS95** [comment]
Ack, better for us so that we don't get the same version desync in the future whenever `windows` bumps again... but I'm not a fan of open-coding everything that was provided by that crate either.

**Comment by amodm** [comment]
Hear hear, and this isn't something I decided lightly.

Documenting my reason - % surface area used of a dependency crate was an important factor here. Very low % on a very fat crate means higher build overhead, and noticeably higher probability of (at least security related) upgrades. The most important gating criteria for the above is that the nature of API used has to be a **very** stable platform API, which I'd verified here.

FWIW, it's the same approach I'm using for `macOS`, and would've likely moved `windows` to the same approach eventually. In both cases, the nature of FFI binding is for very selective, and very stable APIs.

Hope that helps in a better understanding the rationale.

**Comment by MarijnS95** [comment]
I understand the rationale, just dislike the implementation but it's a necessity given how big the `windows` crate is (even when gated by feature flags it's still at least a ±10MB download, for example).

**Pull request merged**
