### PR TITLE
add android support

### PR DESCRIPTION
**Pull request by yazgoo**

### CODE REVIEW

**Comment by amodm** [comment]
Thanks for the contribution, @yazgoo. Can you put up a way to test this as well?

**Comment by yazgoo** [comment]
> Thanks for the contribution, @yazgoo. Can you put up a way to test this as well?

What do you mean ? You'd like me to add a unit test specifically for android ?

**Comment by amodm** [comment]
If you can, yes. https://docs.travis-ci.com/user/languages/android/

Alternatively, put up a piece of simple android code which uses this library and I'll include it in the tests.

**Comment by yazgoo** [comment]
FYI I did not create an android app per se, I'm only compiling/running my rust app in termux ( see https://github.com/yazgoo/youtube-subscriptions/commit/542a87e1f323c5360d215e92c9624277d0905a55#diff-80398c5faae3c069e4e6aa2ed11b28c0R24 )

**Comment by amodm** [comment]
Ok. The reason I was asking was to quickly run that against a variety of android distribs to validate if it succeeds. I don't know enough to check if `am start` works across all android distributions or not. Would you be able to comment on it? Or is it better to follow something along the lines of [this thread](https://groups.google.com/forum/#!topic/android-ndk/SHCXgUCE7t4)

**Comment by amodm** [comment]
Thx for your contribution

**Pull request merged**
