### PR TITLE
Using Core Services in place of /usr/bin/open on macOS

### PR DESCRIPTION
**Pull request by shurizzle**
I created a couple of wrappers around Core Services' frameworks. I'm using OS' APIs to open URLs.

### CODE REVIEW

**Comment by shurizzle** [comment]
```
)> cargo test --all --locked --verbose
       Fresh unicode-xid v0.1.0
       Fresh matches v0.1.8
       Fresh smallvec v0.6.10
       Fresh numtoa v0.0.7
       Fresh void v1.0.2
       Fresh percent-encoding v1.0.1
       Fresh unicode-normalization v0.1.8
       Fresh unicode-bidi v0.3.4
       Fresh fast_fmt v0.1.3
       Fresh proc-macro2 v0.4.30
       Fresh core-foundation-sys v0.6.2
       Fresh libc v0.2.58
       Fresh bitflags v1.1.0
       Fresh quote v0.6.12
       Fresh idna v0.1.5
       Fresh fast_escape v0.1.0
       Fresh syn v0.15.36
       Fresh core-foundation v0.6.4
       Fresh url v1.7.2
       Fresh file-metadata-mditem-macros v0.0.1
       Fresh launch-services v0.0.2
       Fresh file-metadata v0.0.2
       Fresh macos-open v0.0.2
   Compiling webbrowser v0.5.1 (/Volumes/ApplExt/projects/webbrowser-rs)
     Running `rustc --crate-name webbrowser src/lib.rs --color always --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=0cc478eaa6e4d5ee -C extra-filename=-0cc478eaa6e4d5ee --out-dir /Volumes/ApplExt/projects/webbrowser-rs/target/debug/deps -C incremental=/Volumes/ApplExt/projects/webbrowser-rs/target/debug/incremental -L dependency=/Volumes/ApplExt/projects/webbrowser-rs/target/debug/deps --extern macos_open=/Volumes/ApplExt/projects/webbrowser-rs/target/debug/deps/libmacos_open-f0326edec5a841a6.rlib`
     Running `rustc --crate-name webbrowser src/lib.rs --color always --emit=dep-info,link -C debuginfo=2 --test -C metadata=fb0f5a53cdf640fb -C extra-filename=-fb0f5a53cdf640fb --out-dir /Volumes/ApplExt/projects/webbrowser-rs/target/debug/deps -C incremental=/Volumes/ApplExt/projects/webbrowser-rs/target/debug/incremental -L dependency=/Volumes/ApplExt/projects/webbrowser-rs/target/debug/deps --extern macos_open=/Volumes/ApplExt/projects/webbrowser-rs/target/debug/deps/libmacos_open-f0326edec5a841a6.rlib`
    Finished dev [unoptimized + debuginfo] target(s) in 10.44s
     Running `/Volumes/ApplExt/projects/webbrowser-rs/target/debug/deps/webbrowser-fb0f5a53cdf640fb`

running 4 tests
test test_open_chrome ... ignored
test test_open_firefox ... ignored
test test_open_safari ... ignored
test test_open_default ... ok

test result: ok. 1 passed; 0 failed; 3 ignored; 0 measured; 0 filtered out

   Doc-tests webbrowser
     Running `rustdoc --test /Volumes/ApplExt/projects/webbrowser-rs/src/lib.rs --crate-name webbrowser -L dependency=/Volumes/ApplExt/projects/webbrowser-rs/target/debug/deps -L dependency=/Volumes/ApplExt/projects/webbrowser-rs/target/debug/deps --extern macos_open=/Volumes/ApplExt/projects/webbrowser-rs/target/debug/deps/libmacos_open-f0326edec5a841a6.rlib --extern webbrowser=/Volumes/ApplExt/projects/webbrowser-rs/target/debug/deps/libwebbrowser-0cc478eaa6e4d5ee.rlib`

running 4 tests
test src/lib.rs -  (line 21) ... ok
test src/lib.rs - open_browser (line 168) ... ok
test src/lib.rs - open (line 153) ... ok
test src/lib.rs - open (line 146) ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

This is my output on MacBook Pro Mid 2014 with macOS 10.14.5, I don't know why it fails on CI.

**Comment by amodm** [comment]
@shurizzle thanks for the contribution. Given the guaranteed availability of `open` on macOS, I currently see no reason to add an external dependency. Is there any specific advantage to this approach as against `open`?

**Comment by shurizzle** [comment]
image
And you don't need to spawn a new process every time.

**Comment by amodm** [comment]
I hear you on the PATH modification attack - makes sense. When shifting to core-foundation for macOS however, I'd prefer to use it directly instead of going via a wrapper, particularly given the thin & singular nature of abstraction here. Also, the heavy use & regular maintenance of core-foundation would give me a lower risk of dependency adoption. If you feel up to it, it'd be great to receive a PR from you on the same.

**Comment by shurizzle** [comment]
core-foundation is maintained by servo developers and it does not include Core Services' bindings that I made, so macos-open is a kind of sugar around Launch Services and File Metadata's framework (subframeworks of Core Services). To do what you want I'll copy all my code into your repository.

**Comment by amodm** [comment]
You don't have to copy your repo, as it appears much richer than the minimum code needed to make the changes work. From the looks of it, you only need to write implementations of:

- `application_urls_for_bundle_identifier`
- `open_url`
- `open_from_url_spec`

Hopefully I'll be able to shift to your crate `launch-services` at a later point in time, if it becomes the de facto standard in rust world, or if I need to depend on far more functionalities of it. Shifting before then [would mean monitoring bandwidth from my side](https://www.synopsys.com/blogs/software-security/malicious-dependency-supply-chain/), which unfortunately, I can't commit right now.

**Comment by amodm** [comment]
@shurizzle I've already requested you to not use anything other than core-services. I'm sorry if there was any confusion about it. I can't rely on a crate right now that isn't getting heavily used already, as that'd create dependency monitoring effort on my side. Your last commit still uses `launch-services`. You'll need to remove that dependency for me to be able to merge this PR.

**Pull request closed without merging**
