### PR TITLE
Initial AIX enablement

### PR DESCRIPTION
**Pull request by ecnelises**

### CODE REVIEW

**Comment by amodm** [comment]
Thanks. I don't have access to an AIX instance. If you do, can you confirm that the current unix code works for AIX?

**Comment by amodm** [comment]
That works. Some of the test failures have nothing to do with this PR, so I've merged it. I'll update here when this is out as a release.

**Comment by ecnelises** [comment]
Thanks!

**Comment by amodm** [comment]
FYI, this is now released as [v0.8.13](https://github.com/amodm/webbrowser-rs/releases/tag/v0.8.13)

**Pull request merged**
