### PR TITLE
Move to the smaller, cargo-team maintained `home` crate

### PR DESCRIPTION
**Pull request by utkarshgupta137**

### CODE REVIEW

**Comment by amodm** [comment]
The current implementation in the PR is not correct. Please go through this: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by utkarshgupta137** [comment]
Yeah, I deliberately decided to include both paths, in case the user's environment is messed up. I'll change it to the proper spec.

**Comment by amodm** [comment]
Thanks @utkarshgupta137, and congratulations on your first PR here 👏🏼

**Comment by amodm** [comment]
Documenting my reasons for merging this PR, for later reference:
* In general, I favour lighter dependencies, but that's not the main reason here, as the difference between `dirs` vs `home` is just 4kB.
* Doing away with `dirs` means having to take the extra burden of adherence to [XDG Spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), instead of just relying on their `dirs::data_dir()`.
* We already have to be aware of XDG specs, instead of relying just on `xdg-open`, because of our [Guarantee of Consistent Behaviour](https://github.com/amodm/webbrowser-rs#consistent-behaviour)
* Given that we already need to be aware of XDG spec, moving from `dirs` to `home` does not introduce extra complexity for this repo, and only adds to stronger adherence.

**Comment by amodm** [comment]
FYI, this is now released as [v0.8.10](https://github.com/amodm/webbrowser-rs/releases/tag/v0.8.10)

**Pull request merged**
