### PR TITLE
Add support for visionOS

### PR DESCRIPTION
**Pull request by madsmtm**

### CODE REVIEW

**Comment by madsmtm** [comment]
With a custom built toolchain + a forked version of `libc`, it's kinda messy right now

**Comment by madsmtm** [comment]
There's a bit of talk about how to do it in https://github.com/rust-lang/rust/pull/121419 and https://github.com/rust-lang/compiler-team/issues/642, hopefully we'll get https://github.com/rust-lang/libc/pull/3568 merged soon so that `-Zbuild-std` will just work.

**Comment by amodm** [comment]
Principally ok with this. Will merge once I'm able to validate on visionos sim.

**Comment by amodm** [comment]
I was able to validate manually for `visionOS`, so this is good to go, and will get automatically merged via #87

**Comment by amodm** [comment]
This is released as [v1.0.1](https://github.com/amodm/webbrowser-rs/releases/tag/v1.0.1)

**Pull request merged**
